### ISSUE TITLE
ls: cannot access '/ql/log/code': No such file or directory 

### ISSUE THREAD

**Issue by 627992512** [KingRan/JDJB#12]
开始执行... 2021/11/29 下午2:08:18

ls: cannot access '/ql/log/code': No such file or directory
更新任务状态成功

🔔东东农场, 开始!
开始获取配置文件

====================共5个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/11/29 14:08:19=====================

您的东东农场互助码选择的是用&隔开

共5个京东账号

❌ 东东农场, 失败! 原因: TypeError: sc.ModCK is not a function!

🔔东东农场, 结束! 🕛 0.209 秒

更新任务状态成功

执行结束...

大佬，这个是不是只适配了青龙的高版本啊

**Comment by KingRan** [comment]
JDJB
完整库，集合可用脚本，账号互助，不添加助力池，适用于青龙面板。


频道：https://t.me/KingRan521

拉库命令：
青龙面板默认自带代理链接

ql repo https://github.com/KingRan/JDJB.git "jd_|jx_|jdCookie" "activity|backUp" "^jd[^_]|USER|utils|function|sign|sendNotify|ql|JDJR"

**Comment by KingRan** [comment]
你的版本多少？这边没有发现这个问题！

**Comment by 627992512** [comment]
是2.2的老青龙

**Comment by KingRan** [comment]
2.2可以升级了，太老了，已经没有对其测试了。。。。
建议升级新版青龙。
2.2的ck管理会请求京东接口，次数太多就黑IP，会看不到ck的有效的状态！

**Comment by KingRan** [comment]
推荐青龙2.10.2之前2.9之后的版本，当然最新版的也不错。

**Comment by 627992512** [comment]
okok，感谢大佬解答
