### ISSUE TITLE
京东金融、养猪、可以兑换了没有推送消息？

### ISSUE THREAD

**Issue by sw19999** [KingRan/JDJB#13]
其它消息能收到消息，如何设置可以兑换通知？谢谢🙏

**Comment by KingRan** [comment]
请自行查看日志

我这里是有消息推送的！

==============📣系统通知📣==============
金融养猪
京东账号1 
养猪5元立减券已可兑换

京东账号2 
养猪5元立减券已可兑换

京东账号3 
养猪5元立减券已可兑换

**Comment by sw19999** [comment]
/docker/ql/log/KingRan_JDJB_jd_pigPet/2021-11-29-19-25-51.log

日志中间有提示已经可兑换，日志最底下没有提示TG通知信息，东东萌宠和京东农场都有提示。

京东账号7 danny 未开启养猪活动,请手动去京东金融APP开启此活动

开始【京东账号8】hxl薰衣草

【京东账号8】hxl 养猪5元立减券已可兑换，请及时去京东金融APP领取

...
...
...

大转盘助力结果：助力失败，已经助力过了


🔔金融养猪, 结束! 🕛 376.673 秒


## 执行结束... 2021-11-29 19:32:08 耗时 377 秒

**Comment by sw19999** [comment]
青龙2.10.9版本，难道要换成2.10或者2.9版本，这个新版本安装依赖很方便，不用打命令，添加变量那里设置就可以了

**Comment by sw19999** [comment]
今天中午发了一次通知。早上到现在就只收到一次消息，刚刚才去喊同事领取了，一天能收到一次也可以了。



大转盘助力结果：助力失败，已经助力过了

开始发送通知...
通知标题: 金融养猪
Telegram发送通知消息成功🎉。


==============📣系统通知📣==============
金融养猪
京东账号7 hxl薰衣草
养猪5元立减券已可兑换



🔔金融养猪, 结束! 🕛 341.392 秒


## 执行结束... 2021-11-30 12:30:45 耗时 341 秒
