### ISSUE TITLE
关于账号助力的问题

### ISSUE THREAD

**Issue by dnxbice** [KingRan/JDJB#15]
青龙里添加了4个账户，但是在运行一些任务的时候，相应的助力分配是
第1个账户有后3个账户的助力
第2个账户有后2个账户的助力
第3个账户有第4个账户的助力
第4个账户没有助力
或者是完全反过来的
我想问一下作者大大，如何平均分配一下助力，就是达到每个账号都有另外3个账号的助力

**Comment by KingRan** [comment]
重新拉库  之前有车头模式就是这样的情况

**Comment by dnxbice** [comment]
> 重新拉库 之前有车头模式就是这样的情况

重拉之后萌宠是很正常的助力，但是东东农场好像不助力了，额外奖励显示给您人未达2个
