### ISSUE TITLE
财富岛报错了

### ISSUE THREAD

**Issue by afeng116** [KingRan/JDJB#23]
京喜财富岛运行报错了
![image](https://user-images.githubusercontent.com/61038102/148357300-c3b16dce-2fc4-4803-865f-b72aee3461fd.png)

**Comment by KingRan** [comment]
ip黑了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月6日(星期四) 下午5:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [KingRan/JDJB] 财富岛报错了 (Issue #23)





 
京喜财富岛运行报错了
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WZX** [comment]
不是黑了 我研究了半天 是你脚本有个地方错了
最后几行有个1300080426   应该是1200080426
改了就正常了！

**Comment by KingRan** [comment]
方便pr一份嘛&nbsp; &nbsp;我这边正常的&nbsp; 看看你的我运行正常吗！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月7日(星期五) 下午4:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KingRan/JDJB] 财富岛报错了 (Issue #23)





 
不是黑了 我研究了半天 是你脚本有个地方错了
 最后几行有个1300080426   应该是1200080426
 改了就正常了！
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WZX** [comment]
我就拉的你的脚本  只改了这一个地方  
因为本来用的别人的是正常的 今天换成你的库突然出问题了就看了一下
你可以改改运行一下

**Comment by KingRan** [comment]
已经更新了  主要我这边运行是正常的！   所以没法看报错
