### ISSUE TITLE
签到

### ISSUE THREAD

**Issue by hushenan** [KingRan/JDJB#5]
已经解决

**Comment by KingRan** [comment]
这边正常！
JDJB
完整库，集合可用脚本，账号互助，不添加助力池，适用于青龙面板。


频道：https://t.me/KingRan521

拉库命令：
青龙面板默认自带代理链接

ql repo https://github.com/KingRan/JDJB.git "jd_|jx_|jdCookie" "activity|backUp" "^jd[^_]|USER|utils|function|sign|sendNotify|ql|JDJR"

**Comment by hushenan** [comment]
PLUS会员定制 您还不是plus会员，请先开通plus会员吧
"getaddrinfo ENOTFOUND gia.jd.com"

## 执行结束... 2021-11-29 09:37:43 耗时 4 秒

图形签到问题
