### ISSUE TITLE
拉库重复添加定时任务

### ISSUE THREAD

**Issue by houmujiang** [KingRan/JDJB#53]
有时候拉库会重复添加已有的定时任务，不清楚是哪里的问题

**Comment by EchoChan314** [comment]
应该是2.11.1的bug，也可能是GithubProxyUrl设置问题。

**Comment by houmujiang** [comment]
> 应该是2.11.1的bug，也可能是GithubProxyUrl设置问题。

人麻了，无限添加定时任务，服务器给整卡死了😅
